car = ('Engine','Battery','Alternator','Radiator','Steering','Break','Seat Belt')
print('Components of a car: ',car)
print('first element: ',car[0])
print('fourth element: ',car[3])
print('Components of a car from 0 to 4 index: ',car[0: 5])
print('3rd or -7th element: ',car[-7])
print('index of \'Alternator\': ',car.index('Alternator'))
print(' Number of Elements in Car Tuple : ',car.count('Seat Belt'))
print(' Length of Elements in Car Tuple : ',len(car))
